FROM node:20-alpine
WORKDIR /app

# Instala dependências
COPY package.json package-lock.json* ./
RUN npm install

# Source será montado via volume
COPY . .

EXPOSE 5173
CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0"]
